### ISSUE TITLE
First install is installing old version

### ISSUE THREAD

**Issue by UmbraZeal** [JarrettSpiker/FoundryRedirectModule#16]
Redownloading a lot of modules and noticed this mod installs version 1.0.x first and then has to be manually updated to 2.0.3.

**Comment by JarrettSpiker** [comment]
@UmbraZeal thanks for reporting this. Could you share how you install modules? I just tried through the UI and it installed 2.0.3.

I wonder if foundry is keeping  manifest of what versions of extensions it has previously installed somewhere...
