### ISSUE TITLE
[request] Remove my IP from data base as I no longer require this module

### ISSUE THREAD

**Issue by DragonHale** [JarrettSpiker/FoundryRedirectModule#17]
Hello
I don't know where else to contact you about this, I'm sorry about the inconvenience.
I no longer require your module, so I was wondering if it was possible to remove my IP address from the data base you're using.

Thanks in advance.

**Comment by JarrettSpiker** [comment]
@DragonHale yes! Please email me with the URL that the module creates for your world, so I can find it. I will close the ticket and confirm once I have deleted the address.

I will also file an issue to allow this to be done through the module itself

**Comment by JarrettSpiker** [comment]
IP address removed, and I filed #18 to allow this to be done through the module itself in the future.
