### ISSUE TITLE
V11 deprecation warnings

### ISSUE THREAD

**Issue by steamwings** [JarrettSpiker/FoundryRedirectModule#19]
Brand new to Foundry (V11 Build 302). Tried this as my first module. :)

I got the following in Package Warnings when installing:
```
The module "foundry-redirect" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
The module "foundry-redirect" is using "name" which is deprecated in favor of "id"
```
~Not sure if this would prevent the module from working, but my Game Invitation Links are unchanged since installing (and restarting).~ The module is working fine. I hadn't added it to my world. I'll leave this open due to the deprecation warnings, but feel free to close.

Thanks for the work on this module!

**Comment by JarrettSpiker** [comment]
Hi, thanks for reporting this, sorry for the delay!

This should be fixed in version 2.0.4, with this commit https://github.com/JarrettSpiker/FoundryRedirectModule/pull/21/commits/c117c76d1ec177e72f5eb81d3f10f52cfe4f9f42
